[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
env_logger = "0.10.0"
log = "0.4.20"
serde_derive = "=1.0.171"
shared = { path = "../shared" }
